parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''

doctrine:
  dbal:
    # configure these for your database server
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
      oc:
        url: '%env(resolve:DATABASE_URL_OC)%'
        driver: 'pdo_mysql'
        server_version: '5.6'
        charset: utf8mb4
        mapping_types:
          enum:       string
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
  orm:
    default_entity_manager: default
    auto_generate_proxy_classes: '%kernel.debug%'
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          App:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
      oc:
        connection: oc
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
          AppOC:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/OC/Entity'
            prefix: 'App\OC\Entity'
            alias: AppOC
